.TH "src/jpg Directory Reference" 3 "Sat Dec 14 2019" "Codec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/jpg Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjpg_codec\&.c\fP"
.br
.ti -1c
.RI "file \fBjpg_codec\&.h\fP"
.br
.ti -1c
.RI "file \fBjpg_decoder\&.c\fP"
.br
.ti -1c
.RI "file \fBjpg_decoder\&.h\fP"
.br
.ti -1c
.RI "file \fBjpg_encoder\&.c\fP"
.br
.ti -1c
.RI "file \fBjpg_encoder\&.h\fP"
.br
.in -1c
