.TH "src/jpg/jpg_decoder.h" 3 "Sat Dec 14 2019" "Codec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/jpg/jpg_decoder.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBjpg_decode\fP (short *output_array)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int jpg_decode (short * output_array)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Codec from the source code\&.
