.TH "jpg_header_t" 3 "Sat Dec 14 2019" "Codec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpg_header_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBquant_table\fP [64]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t quant_table[64]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Codec from the source code\&.
