.TH "pixel_YCbCr_t" 3 "Sat Dec 14 2019" "Codec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixel_YCbCr_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBY_subpixel\fP"
.br
.ti -1c
.RI "uint8_t \fBCb_subpixel\fP"
.br
.ti -1c
.RI "uint8_t \fBCr_subpixel\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t Cb_subpixel"

.SS "uint8_t Cr_subpixel"

.SS "uint8_t Y_subpixel"


.SH "Author"
.PP 
Generated automatically by Doxygen for Codec from the source code\&.
