.TH "pixel_rgb_buffer_t" 3 "Sat Dec 14 2019" "Codec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pixel_rgb_buffer_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpixel_rgb_t\fP * \fBp_buff\fP"
.br
.ti -1c
.RI "uint64_t \fBsize\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBpixel_rgb_t\fP* p_buff"

.SS "uint64_t size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Codec from the source code\&.
